theme: jekyll-theme-minimal
title: Kaldi Community Roadmap
description: A series of virtual meetings to set the path forward
logo: https://kaldi-asr.org/kaldi_text_and_logo.png
google_analytics: UA-177849724-1
